<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testPackage" nsURI="http://rtt/ui/ecore/tests" nsPrefix="rtt.ui.ecore.tests">
  <eClassifiers xsi:type="ecore:EClass" name="TestParser">
    <eOperations name="TestOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TestAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestNode">
    <eOperations name="TestOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TestAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestReference"/>
  </eClassifiers>
</ecore:EPackage>
